package com.asitkg.bmitracker.ui.auth

import android.app.Activity
import android.content.Context
import android.content.ContextWrapper
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.asitkg.bmitracker.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * Obtains a Google ID token via Credential Manager.
 *
 * This lives in the UI layer because Credential Manager needs an Activity to
 * show its account sheet; the token alone is handed to the view model, keeping
 * Android UI types out of it.
 *
 * Credential Manager replaces the deprecated GoogleSignInClient API.
 */
sealed interface GoogleSignInOutcome {

    data class Success(val idToken: String) : GoogleSignInOutcome

    /** User dismissed the sheet — not an error, so no message is shown. */
    data object Cancelled : GoogleSignInOutcome

    data class Failure(val message: String) : GoogleSignInOutcome
}

suspend fun requestGoogleIdToken(context: Context): GoogleSignInOutcome {
    val activity = context.findActivity()
        ?: return GoogleSignInOutcome.Failure("Could not start Google sign-in.")

    // default_web_client_id is generated by the google-services plugin from the
    // client_type 3 entry in google-services.json. A missing resource here means
    // Google sign-in was not enabled before that file was downloaded.
    val serverClientId = context.getString(R.string.default_web_client_id)

    val googleIdOption = GetGoogleIdOption.Builder()
        // false so an account picker is shown even when none is yet linked;
        // filtering to authorised accounts only would make first sign-in fail
        // with NoCredentialException.
        .setFilterByAuthorizedAccounts(false)
        .setServerClientId(serverClientId)
        .setAutoSelectEnabled(false)
        .build()

    val request = GetCredentialRequest.Builder()
        .addCredentialOption(googleIdOption)
        .build()

    return try {
        val response = CredentialManager.create(activity).getCredential(activity, request)
        val credential = response.credential

        if (credential is CustomCredential &&
            credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            GoogleSignInOutcome.Success(
                GoogleIdTokenCredential.createFrom(credential.data).idToken,
            )
        } else {
            GoogleSignInOutcome.Failure("Unexpected credential type returned.")
        }
    } catch (e: GetCredentialCancellationException) {
        GoogleSignInOutcome.Cancelled
    } catch (e: NoCredentialException) {
        GoogleSignInOutcome.Failure("No Google account found on this device.")
    } catch (e: GetCredentialException) {
        GoogleSignInOutcome.Failure(e.message ?: "Google sign-in failed.")
    }
}

private fun Context.findActivity(): Activity? {
    var current: Context = this
    while (current is ContextWrapper) {
        if (current is Activity) return current
        current = current.baseContext
    }
    return null
}
